<?php
use App\Controllers\Api\AuthController;
use App\Controllers\Api\AdController;
use App\Controllers\Api\AdminController;
use App\Controllers\Api\ChatController;
use App\Controllers\Api\HealthController;
use App\Controllers\Api\AiController;
use App\Controllers\Api\NotificationController;
use App\Controllers\Api\PostController;
use App\Controllers\Api\ProfileController;
use App\Controllers\Api\ReportController;
use App\Controllers\Api\SearchController;
use App\Controllers\Api\SettingsController;
use App\Controllers\Api\StoryController;
use App\Controllers\Api\UserController;
use App\Middleware\AdminMiddleware;
use App\Middleware\AuthMiddleware;
use App\Middleware\RateLimitMiddleware;

$router->group(['prefix' => '/api'], function ($router) {
    $router->get('/health', [HealthController::class, 'status']);
    $router->post('/auth/register', [AuthController::class, 'register'], [new RateLimitMiddleware(10, 60)]);
    $router->post('/auth/login', [AuthController::class, 'login'], [new RateLimitMiddleware(20, 60)]);
    $router->post('/auth/logout', [AuthController::class, 'logout'], [AuthMiddleware::class]);
    $router->get('/auth/verify-email', [AuthController::class, 'verifyEmail']);
    $router->post('/auth/resend-verification', [AuthController::class, 'resendVerification'], [AuthMiddleware::class]);
    $router->post('/auth/request-account-change', [AuthController::class, 'requestAccountChange'], [AuthMiddleware::class]);
    $router->get('/auth/confirm-account-change', [AuthController::class, 'confirmAccountChange']);
    $router->get('/auth/me', [AuthController::class, 'me'], [AuthMiddleware::class]);

    $router->get('/profile/{id}', [ProfileController::class, 'overview'], [AuthMiddleware::class]);
    $router->put('/profile/intro', [ProfileController::class, 'updateIntro'], [AuthMiddleware::class]);
    $router->get('/profile/{id}/posts', [ProfileController::class, 'posts'], [AuthMiddleware::class]);
    $router->get('/profile/{id}/friends', [ProfileController::class, 'friends'], [AuthMiddleware::class]);
    $router->get('/profile/{id}/media', [ProfileController::class, 'media'], [AuthMiddleware::class]);
    $router->get('/profile/{id}/tagged', [ProfileController::class, 'tagged'], [AuthMiddleware::class]);
    $router->get('/profile/{id}/activity', [ProfileController::class, 'activity'], [AuthMiddleware::class]);
    $router->get('/profile/{id}/highlights', [ProfileController::class, 'highlights'], [AuthMiddleware::class]);
    $router->get('/profile/highlights/{id}/items', [ProfileController::class, 'highlightItems'], [AuthMiddleware::class]);
    $router->post('/profile/highlights', [ProfileController::class, 'createHighlight'], [AuthMiddleware::class]);
    $router->post('/profile/highlights/{id}/items', [ProfileController::class, 'addHighlightItem'], [AuthMiddleware::class]);
    $router->delete('/profile/highlights/{id}', [ProfileController::class, 'deleteHighlight'], [AuthMiddleware::class]);
    $router->delete('/profile/highlights/items/{itemId}', [ProfileController::class, 'deleteHighlightItem'], [AuthMiddleware::class]);
    $router->get('/profile/{id}/albums', [ProfileController::class, 'albums'], [AuthMiddleware::class]);
    $router->get('/profile/albums/{id}/items', [ProfileController::class, 'albumItems'], [AuthMiddleware::class]);
    $router->post('/profile/albums', [ProfileController::class, 'createAlbum'], [AuthMiddleware::class]);
    $router->post('/profile/albums/{id}/items', [ProfileController::class, 'addAlbumItem'], [AuthMiddleware::class]);
    $router->delete('/profile/albums/{id}', [ProfileController::class, 'deleteAlbum'], [AuthMiddleware::class]);
    $router->delete('/profile/albums/items/{itemId}', [ProfileController::class, 'deleteAlbumItem'], [AuthMiddleware::class]);
    $router->get('/profile/{id}/pins', [ProfileController::class, 'pins'], [AuthMiddleware::class]);
    $router->post('/profile/pins', [ProfileController::class, 'pinPost'], [AuthMiddleware::class]);
    $router->delete('/profile/pins/{id}', [ProfileController::class, 'unpinPost'], [AuthMiddleware::class]);
    $router->get('/profile/{id}/groups', [ProfileController::class, 'groups'], [AuthMiddleware::class]);
    $router->post('/profile/groups', [ProfileController::class, 'createGroup'], [AuthMiddleware::class]);
    $router->get('/profile/{id}/pages', [ProfileController::class, 'pages'], [AuthMiddleware::class]);
    $router->post('/profile/pages', [ProfileController::class, 'createPage'], [AuthMiddleware::class]);
    $router->get('/profile/{id}/events', [ProfileController::class, 'events'], [AuthMiddleware::class]);
    $router->post('/profile/events', [ProfileController::class, 'createEvent'], [AuthMiddleware::class]);

    $router->get('/users/active', [UserController::class, 'activeUsers'], [AuthMiddleware::class]);
    $router->get('/users/{id}', [UserController::class, 'show'], [AuthMiddleware::class]);
    $router->get('/users/{id}/posts', [UserController::class, 'posts'], [AuthMiddleware::class]);
    $router->put('/users/me', [UserController::class, 'update'], [AuthMiddleware::class]);
    $router->post('/users/me/media', [UserController::class, 'uploadMedia'], [AuthMiddleware::class]);
    $router->post('/users/{id}/follow', [UserController::class, 'follow'], [AuthMiddleware::class]);
    $router->post('/follow-requests/{id}/accept', [UserController::class, 'acceptFollowRequest'], [AuthMiddleware::class]);
    $router->delete('/users/{id}/follow', [UserController::class, 'unfollow'], [AuthMiddleware::class]);
    $router->post('/users/{id}/friend-request', [UserController::class, 'sendFriendRequest'], [AuthMiddleware::class]);
    $router->post('/friend-requests/{id}/accept', [UserController::class, 'acceptFriendRequest'], [AuthMiddleware::class]);
    $router->post('/friend-requests/{id}/reject', [UserController::class, 'rejectFriendRequest'], [AuthMiddleware::class]);
    $router->get('/friend-requests', [UserController::class, 'listFriendRequests'], [AuthMiddleware::class]);
    $router->get('/follow-requests', [UserController::class, 'listFollowRequests'], [AuthMiddleware::class]);
    $router->post('/follow-requests/{id}/reject', [UserController::class, 'rejectFollowRequest'], [AuthMiddleware::class]);
    $router->post('/users/me/status', [UserController::class, 'status'], [AuthMiddleware::class]);
    $router->post('/users/{id}/block', [UserController::class, 'block'], [AuthMiddleware::class]);
    $router->post('/users/{id}/unblock', [UserController::class, 'unblock'], [AuthMiddleware::class]);
    $router->get('/blocks', [UserController::class, 'blockedList'], [AuthMiddleware::class]);
    $router->get('/sessions', [UserController::class, 'sessions'], [AuthMiddleware::class]);
    $router->post('/sessions/{id}/revoke', [UserController::class, 'revokeSession'], [AuthMiddleware::class]);
    $router->post('/users/me/password', [UserController::class, 'changePassword'], [AuthMiddleware::class]);
    $router->get('/users/suggestions', [UserController::class, 'suggestions'], [AuthMiddleware::class]);

    $router->post('/posts', [PostController::class, 'create'], [AuthMiddleware::class]);
    $router->get('/posts/feed', [PostController::class, 'feed'], [AuthMiddleware::class]);
    $router->post('/posts/{id}/like', [PostController::class, 'like'], [AuthMiddleware::class]);
    $router->delete('/posts/{id}/like', [PostController::class, 'unlike'], [AuthMiddleware::class]);
    $router->post('/posts/{id}/comment', [PostController::class, 'comment'], [AuthMiddleware::class]);
    $router->get('/posts/{id}/comments', [PostController::class, 'comments'], [AuthMiddleware::class]);
    $router->post('/posts/{id}/share', [PostController::class, 'share'], [AuthMiddleware::class]);
    $router->post('/posts/{id}/bookmark', [PostController::class, 'bookmark'], [AuthMiddleware::class]);
    $router->post('/posts/{id}/tag', [PostController::class, 'tag'], [AuthMiddleware::class]);

    $router->get('/search', [SearchController::class, 'index'], [AuthMiddleware::class]);
    $router->get('/search/friends', [SearchController::class, 'friends'], [AuthMiddleware::class]);
    $router->get('/settings', [SettingsController::class, 'show'], [AuthMiddleware::class]);
    $router->put('/settings', [SettingsController::class, 'update'], [AuthMiddleware::class]);
    $router->get('/ads/active', [AdController::class, 'active'], [AuthMiddleware::class]);

    $router->post('/reports', [ReportController::class, 'create'], [AuthMiddleware::class]);

    $router->get('/stories', [StoryController::class, 'index'], [AuthMiddleware::class]);
    $router->post('/stories', [StoryController::class, 'create'], [AuthMiddleware::class]);
    $router->post('/stories/{id}/view', [StoryController::class, 'view'], [AuthMiddleware::class]);
    $router->get('/stories/{id}/viewers', [StoryController::class, 'viewers'], [AuthMiddleware::class]);
    $router->post('/stories/{id}/reply', [StoryController::class, 'reply'], [AuthMiddleware::class]);
    $router->get('/stories/{id}/replies', [StoryController::class, 'replies'], [AuthMiddleware::class]);

    $router->post('/conversations', [ChatController::class, 'createConversation'], [AuthMiddleware::class]);
    $router->get('/conversations', [ChatController::class, 'listConversations'], [AuthMiddleware::class]);
    $router->get('/message-requests', [ChatController::class, 'listMessageRequests'], [AuthMiddleware::class]);
    $router->post('/message-requests/{id}/accept', [ChatController::class, 'acceptMessageRequest'], [AuthMiddleware::class]);
    $router->post('/message-requests/{id}/deny', [ChatController::class, 'denyMessageRequest'], [AuthMiddleware::class]);
    $router->get('/conversations/{id}/messages', [ChatController::class, 'messages'], [AuthMiddleware::class]);
    $router->post('/conversations/{id}/messages', [ChatController::class, 'sendMessage'], [AuthMiddleware::class]);
    $router->post('/conversations/{id}/messages/media', [ChatController::class, 'sendMedia'], [AuthMiddleware::class]);
    $router->get('/conversations/{id}/typing', [ChatController::class, 'typingState'], [AuthMiddleware::class]);
    $router->post('/conversations/{id}/typing', [ChatController::class, 'typing'], [AuthMiddleware::class]);
    $router->post('/messages/{id}/read', [ChatController::class, 'read'], [AuthMiddleware::class]);
    $router->get('/messages/{id}/edits', [ChatController::class, 'edits'], [AuthMiddleware::class]);
    $router->put('/messages/{id}', [ChatController::class, 'edit'], [AuthMiddleware::class]);
    $router->delete('/messages/{id}', [ChatController::class, 'delete'], [AuthMiddleware::class]);
    $router->post('/messages/{id}/reactions', [ChatController::class, 'react'], [AuthMiddleware::class]);
    $router->post('/conversations/{id}/pin', [ChatController::class, 'pin'], [AuthMiddleware::class]);
    $router->post('/conversations/{id}/unpin', [ChatController::class, 'unpin'], [AuthMiddleware::class]);
    $router->post('/conversations/{id}/mute', [ChatController::class, 'mute'], [AuthMiddleware::class]);
    $router->post('/conversations/{id}/unmute', [ChatController::class, 'unmute'], [AuthMiddleware::class]);
    $router->post('/realtime/auth', [ChatController::class, 'realtimeAuth'], [AuthMiddleware::class]);

    $router->get('/notifications', [NotificationController::class, 'index'], [AuthMiddleware::class]);
    $router->post('/notifications/{id}/read', [NotificationController::class, 'markRead'], [AuthMiddleware::class]);
    $router->post('/notifications/read-all', [NotificationController::class, 'markAllRead'], [AuthMiddleware::class]);
    $router->delete('/notifications/{id}', [NotificationController::class, 'delete'], [AuthMiddleware::class]);
    $router->delete('/notifications', [NotificationController::class, 'clear'], [AuthMiddleware::class]);

    $router->post('/ai/suggest-replies', [AiController::class, 'suggestReplies'], [AuthMiddleware::class]);
    $router->post('/ai/tone-check', [AiController::class, 'toneCheck'], [AuthMiddleware::class]);
    $router->post('/ai/phishing-check', [AiController::class, 'phishingCheck'], [AuthMiddleware::class]);
    $router->post('/ai/summarize', [AiController::class, 'summarize'], [AuthMiddleware::class]);
    $router->post('/ai/reminder', [AiController::class, 'reminder'], [AuthMiddleware::class]);
    $router->post('/ai/translate', [AiController::class, 'translate'], [AuthMiddleware::class]);

    $router->get('/admin/metrics', [AdminController::class, 'metrics'], [AuthMiddleware::class, AdminMiddleware::class]);
    $router->get('/admin/users', [AdminController::class, 'users'], [AuthMiddleware::class, AdminMiddleware::class]);
    $router->post('/admin/users/{id}/status', [AdminController::class, 'setStatus'], [AuthMiddleware::class, AdminMiddleware::class]);
    $router->post('/admin/users/{id}/role', [AdminController::class, 'setRole'], [AuthMiddleware::class, AdminMiddleware::class]);
    $router->get('/admin/reports', [AdminController::class, 'reports'], [AuthMiddleware::class, AdminMiddleware::class]);
    $router->post('/admin/reports/{id}/resolve', [AdminController::class, 'resolveReport'], [AuthMiddleware::class, AdminMiddleware::class]);
    $router->get('/admin/ads', [AdminController::class, 'ads'], [AuthMiddleware::class, AdminMiddleware::class]);
    $router->post('/admin/ads', [AdminController::class, 'createAd'], [AuthMiddleware::class, AdminMiddleware::class]);
    $router->post('/admin/ads/{id}/deactivate', [AdminController::class, 'deactivateAd'], [AuthMiddleware::class, AdminMiddleware::class]);
    $router->get('/admin/alerts', [AdminController::class, 'alerts'], [AuthMiddleware::class, AdminMiddleware::class]);
    $router->post('/admin/alerts/{id}/read', [AdminController::class, 'markAlertRead'], [AuthMiddleware::class, AdminMiddleware::class]);
    $router->post('/admin/alerts/read-all', [AdminController::class, 'markAllAlertsRead'], [AuthMiddleware::class, AdminMiddleware::class]);
    $router->delete('/admin/alerts/{id}', [AdminController::class, 'deleteAlert'], [AuthMiddleware::class, AdminMiddleware::class]);
});
